RC = [
 (0x0684704c,0xe620c00a,0xb2c5fef0,0x75817b9d),(0x8b66b4e1,0x88f3a06b,0x640f6ba4,0x2f08f717),
 (0x3402de2d,0x53f28498,0xcf029d60,0x9f029114),(0x0ed6eae6,0x2e7b4f08,0xbbf3bcaf,0xfd5b4f79),
 (0xcbcfb0cb,0x4872448b,0x79eecd1c,0xbe397044),(0x7eeacdee,0x6e9032b7,0x8d5335ed,0x2b8a057b),
 (0x67c28f43,0x5e2e7cd0,0xe2412761,0xda4fef1b),(0x2924d9b0,0xafcacc07,0x675ffde2,0x1fc70b3b),
 (0xab4d63f1,0xe6867fe9,0xecdb8fca,0xb9d465ee),(0x1c30bf84,0xd4b7cd64,0x5b2a404f,0xad037e33),
 (0xb2cc0bb9,0x941723bf,0x69028b2e,0x8df69800),(0xfa0478a6,0xde6f5572,0x4aaa9ec8,0x5c9d2d8a),
 (0xdfb49f2b,0x6b772a12,0x0efa4f2e,0x29129fd4),(0x1ea10344,0xf449a236,0x32d611ae,0xbb6a12ee),
 (0xaf044988,0x4b050084,0x5f9600c9,0x9ca8eca6),(0x21025ed8,0x9d199c4f,0x78a2c7e3,0x27e593ec),
 (0xbf3aaaf8,0xa759c9b7,0xb9282ecd,0x82d40173),(0x6260700d,0x6186b017,0x37f2efd9,0x10307d6b),
 (0x5aca45c2,0x21300443,0x81c29153,0xf6fc9ac6),(0x9223973c,0x226b68bb,0x2caf92e8,0x36d1943a),
 (0xd3bf9238,0x225886eb,0x6cbab958,0xe51071b4),(0xdb863ce5,0xaef0c677,0x933dfddd,0x24e1128d),
 (0xbb606268,0xffeba09c,0x83e48de3,0xcb2212b1),(0x734bd3dc,0xe2e4d19c,0x2db91a4e,0xc72bf77d),
 (0x43bb47c3,0x61301b43,0x4b1415c4,0x2cb3924e),(0xdba775a8,0xe707eff6,0x03b231dd,0x16eb6899),
 (0x6df3614b,0x3c755977,0x8e5e2302,0x7eca472c),(0xcda75a17,0xd6de7d77,0x6d1be5b9,0xb88617f9),
 (0xec6b43f0,0x6ba8e9aa,0x9d6c069d,0xa946ee5d),(0xcb1e6950,0xf957332b,0xa2531159,0x3bf327c1),
 (0x2cee0c75,0x00da619c,0xe4ed0353,0x600ed0d9),(0xf0b1a5a1,0x96e90cab,0x80bbbabc,0x63a4a350),
 (0xae3db102,0x5e962988,0xab0dde30,0x938dca39),(0x17bb8f38,0xd554a40b,0x8814f3a8,0x2e75b442),
 (0x34bb8a5b,0x5f427fd7,0xaeb6b779,0x360a16f6),(0x26f65241,0xcbe55438,0x43ce5918,0xffbaafde),
 (0x4ce99a54,0xb9f3026a,0xa2ca9cf7,0x839ec978),(0xae51a51a,0x1bdff7be,0x40c06e28,0x22901235),
 (0xa0c1613c,0xba7ed22b,0xc173bc0f,0x48a659cf),(0x756acc03,0x02288288,0x4ad6bdfd,0xe9c59da1),
]
# _mm_set_epi32(e3,e2,e1,e0) puts e0 in words[0].
W = [ (t[3], t[2], t[1], t[0]) for t in RC ]

def lo32(a,b): return (a[0], b[0], a[1], b[1])
def hi32(a,b): return (a[2], b[2], a[3], b[3])

def fmt(v): return "{0x%08x, 0x%08x, 0x%08x, 0x%08x}" % v

out = []
out.append("// Generated by tools/gen_tables.py -- do not edit by hand.")
out.append("//")
out.append("// Words are stored in memory order, so word[0] is the low 32 bits: the")
out.append("// upstream tables are written as _mm_set_epi32(e3,e2,e1,e0), which places")
out.append("// e0 first. vld1q_u32 then reproduces the x86 register exactly.")
out.append("#pragma once")
out.append("#include <stdint.h>")
out.append("")
out.append("namespace vh22 {")
out.append("")
out.append("// The 40 Haraka round constants.")
out.append("alignas(16) inline constexpr uint32_t kHarakaRC[40][4] = {")
for i in range(0, 40, 2):
    out.append("\t%s, %s," % (fmt(W[i]), fmt(W[i+1])))
out.append("};")
out.append("")
out.append("// Same absorption for Haraka256's five AES2+MIX2 groups (key expansion).")
out.append("//   kHaraka256Absorb[g][0..1] = MIX2(rc[4g+2], rc[4g+3])")
out.append("alignas(16) inline constexpr uint32_t kHaraka256Absorb[5][2][4] = {")
for g in range(5):
    a, b = W[4*g+2], W[4*g+3]
    out.append("\t{%s, %s}," % (fmt(lo32(a,b)), fmt(hi32(a,b))))
out.append("};")
out.append("")
out.append("} // namespace vh22")
open("/Users/brandon/verusminer/vh22/include/vh22/haraka_tables.h","w").write("\n".join(out) + "\n")
print("wrote", len(out), "lines")
